version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    hostname: node1
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - rabbitmq:/var/lib/rabbitmq
  filebeat:
    image: docker.elastic.co/beats/filebeat-oss:7.8.0
    container_name: filebeat
    depends_on:
      - elasticsearch
      - logstash
    volumes:
      - filebeat:/usr/share/filebeat/data
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      - /home/dmi3/RubymineProjects/ads/log:/var/log/ads:ro
      - /home/dmi3/RubymineProjects/geocoder/log:/var/log/geocoder:ro
      - /home/dmi3/RubymineProjects/auth/log:/var/log/auth:ro
  logstash:
    image: docker.elastic.co/logstash/logstash-oss:7.8.0
    container_name: logstash
    depends_on:
      - elasticsearch
    volumes:
      - logstash:/usr/share/logstash/data
      - ./logstash/pipeline/:/usr/share/logstash/pipeline/
      - ./logstash/logstash.yml:/usr/share/logstash/config/logstash.yml
    ports:
      - "5046:5046" #tcp
      - "9600:9600"
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.8.0
    container_name: elasticsearch
    volumes:
      - elasticsearch:/usr/share/elasticsearch/data
      - ./elasticsearch/elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml
    ports:
      - "9200:9200"
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:7.8.0
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    ports:
      - "5601:5601"
  prom:
    image: prom/prometheus
    container_name: prom
    network_mode: host
    volumes:
      - prometheus:/prometheus
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
  grafana:
    image: grafana/grafana
    container_name: grafana
    extra_hosts:
      - "host.docker.internal:host-gateway"
    depends_on:
      - prom
    ports:
      - "3100:3000"
    volumes:
      - grafana:/var/lib/grafana

volumes:
  rabbitmq:
  filebeat:
  elasticsearch:
  logstash:
  prometheus:
  grafana:
