global:
  scrape_interval: 15s

scrape_configs:
  - job_name: node
    static_configs:
      - targets:
          - localhost:9100

  - job_name: services
    static_configs:
      - targets:
          - localhost:9292
          - localhost:9293
          - localhost:9294
